# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  aspnet-core:
    image: docker.io/bitnami/aspnet-core:8
    command: ["tail", "-f", "/dev/null"] # To keep the container running
    volumes:
      - aspnet-core_data:/app
volumes:
  aspnet-core_data:
    driver: local
