# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  php:
    tty: true # Enables debugging capabilities when attached to this container.
    image: docker.io/bitnami/php-fpm:8.3
    ports:
      - 9000:9000
    volumes:
      - .:/app
